<?php

/* ***************************************************************************** */
/* THEME INITIALIZATION                                                          */
/* ***************************************************************************** */
/* Do not edit this file                                                         */
/* ***************************************************************************** */


// LOAD THEME CONFIGURATION
require_once(__DIR__ . '/config.php');


// LOAD THEME INCLUDES/DEPENDENCIES
require_once(__DIR__ . '/includes/acf/acf.php');


// LOAD THEME CORE
require_once(__DIR__ . '/core/core.php');
require_once(__DIR__ . '/core/tools.php');
require_once(__DIR__ . '/core/debug.php');


// LOAD THEME COMPONENTS
require_once(__DIR__ . '/components/cleanup.php');
require_once(__DIR__ . '/components/enqueues.php');
require_once(__DIR__ . '/components/post-types.php');
require_once(__DIR__ . '/components/menus.php');
require_once(__DIR__ . '/components/image-sizes.php');
require_once(__DIR__ . '/components/fonts.php');
require_once(__DIR__ . '/components/redirects.php');
require_once(__DIR__ . '/components/cronjobs.php');
require_once(__DIR__ . '/components/shortcodes.php');
require_once(__DIR__ . '/components/widgets.php');
require_once(__DIR__ . '/components/editor.php');
require_once(__DIR__ . '/components/emails.php');


// LOAD WORDPRESS ADMIN PANEL CUSTOMIZATIONS
require_once(__DIR__ . '/admin/admin.php');
require_once(__DIR__ . '/admin/options-pages.php');


// SET THEME TEXT DOMAIN
function theme_init() {
    load_theme_textdomain( 'hiiukala-theme', get_template_directory() . '/translations' );
}

?>